// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Hardcoded Supabase credentials for development
const SUPABASE_URL = "https://aftiuxltgxqwgsnylgtm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFmdGl1eGx0Z3hxd2dzbnlsZ3RtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0NzYwMjQsImV4cCI6MjA2MDA1MjAyNH0.Oa9BCNPJsSHfU2Or6u_FsdpSB2SXZ7v7c6iZcpow-R8";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);